### ISSUE TITLE
Devices are not found

### ISSUE THREAD

**Issue by dereulenspiegel** [aheil/openhab#3]
I'm getting the following message in my log:

16:31:09.427 INFO  o.o.b.m.i.MaxCubeBinding[:153]- Cannot find MAX!cube device with serial number 'JEQ0501207'
16:31:09.429 INFO  o.o.b.m.i.MaxCubeBinding[:153]- Cannot find MAX!cube device with serial number 'KEQ0493700'
16:31:09.431 INFO  o.o.b.m.i.MaxCubeBinding[:153]- Cannot find MAX!cube device with serial number 'JEQ0607538'
16:31:09.434 INFO  o.o.b.m.i.MaxCubeBinding[:153]- Cannot find MAX!cube device with serial number 'KEQ0098486'
16:31:09.436 INFO  o.o.b.m.i.MaxCubeBinding[:153]- Cannot find MAX!cube device with serial number 'KEQ0493700'
It seems that none of my devices are found. In the past, I at least could read the desired temperature of the thermostats and received the window state.
But I can see in the DEBUG log tha H, C, M and L messages are received.
Here is an example of one of my item configs:
Contact Window_Bedroom  "Fenster im Schlafzimmer ist [MAP(de.map):%s]" (Bedroom,Windows,OpenWindows) {maxcube="JEQ0607538"}

**Comment by dereulenspiegel** [comment]
After my last build of your binding I'm getting now the following messages in my log:
15:36:45.754 WARN  o.o.b.m.i.MaxCubeBinding[:187]- Cannot read data from MAX!cube lan gateway while connecting to '192.168.100.57'

My Cube had an Firmwareupdate is it possible that it changed the protocol?

**Comment by aheil** [comment]
Thanks for the feedback. I have added debugging output to the logger. Could you please try with the latest revision of my fork? The log should now include the stack trace on debugging log level.

Usually this might caused by an network error or maybe wrong IP of the cube. The stack trace should tell us the issue here. This issue happens when opening the TCP port to the cube, at this point there are no information about the protcol version available. However, maybe they changed the port the cube is using.

Considering the first post, could you please check the log file for the H message data (of course this will work only if the connection worked before ).

It should look similar to 

16:10:28.588 DEBUG o.o.b.m.i.MaxCubeBinding[:74] - === H_Message === 
16:10:28.589 DEBUG o.o.b.m.i.MaxCubeBinding[:75] -  RAW:JEQ0304492,01edb1,0112,00000000,2e943f81,01,32,0d0b01,100a,03,0000
16:10:28.591 DEBUG o.o.b.m.i.MaxCubeBinding[:76] -  Reading Time: Fri Dec 01 16:10:00 CET 13
16:10:28.591 DEBUG o.o.b.m.i.MaxCubeBinding[:77] -  Serial number:  JEQ0304492
16:10:28.592 DEBUG o.o.b.m.i.MaxCubeBinding[:78] -  RF address (HEX):01edb1
16:10:28.592 DEBUG o.o.b.m.i.MaxCubeBinding[:79] -  Firmware version:0112
16:10:28.592 DEBUG o.o.b.m.i.MaxCubeBinding[:80] -  Connection ID: 2e943f81 

and tell about the firmware.

Thanks a lot for testing!

**Comment by dereulenspiegel** [comment]
I build a new version of the binding and now I'm getting the following log entries:
19:27:51.230 DEBUG o.o.b.m.i.MaxCubeActivator[:31]- MAX!Cube LAN gateway binding has been started.
19:27:51.328 INFO  o.o.c.s.AbstractActiveService[:189]- MAX!Cube Refresh Service has been started
19:27:51.338 INFO  o.o.b.m.i.MaxCubeBinding[:201]- Cannot read data from MAX!cube lan gateway while connecting to '192.168.100.57'
19:27:51.348 DEBUG o.o.b.m.i.MaxCubeBinding[:202]- java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:579)
        at java.net.Socket.connect(Socket.java:528)
        at java.net.Socket.<init>(Socket.java:425)
        at java.net.Socket.<init>(Socket.java:208)
        at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:114)
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:176)
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:193)

19:28:01.548 DEBUG o.o.b.m.i.MaxCubeBinding[:74]- === H_Message ===
19:28:01.551 DEBUG o.o.b.m.i.MaxCubeBinding[:75]-       RAW:JEQ0544462,03f482,0113,00000000,5bf935ab,00,32,0d0b01,131c,03,0000
19:28:01.553 DEBUG o.o.b.m.i.MaxCubeBinding[:76]-       Reading Time: Fri Dec 01 19:28:00 CET 13
19:28:01.558 DEBUG o.o.b.m.i.MaxCubeBinding[:77]-       Serial number:  JEQ0544462
19:28:01.563 DEBUG o.o.b.m.i.MaxCubeBinding[:78]-       RF address (HEX):03f482
19:28:01.565 DEBUG o.o.b.m.i.MaxCubeBinding[:79]-       Firmware version:0113
19:28:01.575 DEBUG o.o.b.m.i.MaxCubeBinding[:80]-       Connection ID: 5bf935ab
19:28:01.596 DEBUG o.o.b.m.i.MaxCubeBinding[:28]- === M_Message ===
19:28:01.698 DEBUG o.o.b.m.i.message.C_Message[:51]- C_Message malformed: wrong data length. Expected bytes 237, actual bytes []
19:28:01.701 DEBUG o.o.b.m.i.message.C_Message[:56]- C_Message malformed: wrong RF address. Expected address 03f482, actual address []
19:28:01.706 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
19:28:01.797 DEBUG o.o.b.m.i.message.C_Message[:51]- C_Message malformed: wrong data length. Expected bytes 206, actual bytes []
19:28:01.800 DEBUG o.o.b.m.i.message.C_Message[:56]- C_Message malformed: wrong RF address. Expected address 058174, actual address []
19:28:01.802 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
19:28:01.805 DEBUG o.o.b.m.i.message.C_Message[:51]- C_Message malformed: wrong data length. Expected bytes 210, actual bytes []
19:28:01.807 DEBUG o.o.b.m.i.message.C_Message[:56]- C_Message malformed: wrong RF address. Expected address 076843, actual address []
19:28:01.809 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
19:28:01.811 DEBUG o.o.b.m.i.message.C_Message[:51]- C_Message malformed: wrong data length. Expected bytes 210, actual bytes []
19:28:01.813 DEBUG o.o.b.m.i.message.C_Message[:56]- C_Message malformed: wrong RF address. Expected address 097887, actual address []
19:28:01.816 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
19:28:01.818 DEBUG o.o.b.m.i.message.C_Message[:51]- C_Message malformed: wrong data length. Expected bytes 17, actual bytes []
19:28:01.820 DEBUG o.o.b.m.i.message.C_Message[:56]- C_Message malformed: wrong RF address. Expected address 0623ec, actual address []
19:28:01.822 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
19:28:01.896 DEBUG o.o.b.m.i.MaxCubeBinding[:50]- === L_Message ===
19:28:01.914 INFO  o.o.b.m.i.MaxCubeBinding[:148]- Failed to process message received by MAX! protocol.
19:28:01.917 DEBUG o.o.b.m.i.MaxCubeBinding[:149]- java.lang.NullPointerException
        at org.openhab.binding.maxcube.internal.message.Device.create(Device.java:90)
        at org.openhab.binding.maxcube.internal.message.L_Message.getDevices(L_Message.java:42)
        at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:136)
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:176)
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:193)

Despite the Exception it seems that a H message is still received. Probably only the first connect failed. Nmap shows that the tcp port 62910 is open.

**Comment by dereulenspiegel** [comment]
I just wanted to ask if there is any progress on this issue? Unfortunately this binding is currently completely unusable for.

**Comment by aheil** [comment]
I just updated the debug output for the binding. RF address and payload length are now correctly compared. Still cannot reproduce this issue. Maybe you could check with the current revision again if the error still exists?

**Comment by dereulenspiegel** [comment]
Hi!

I build your branch and updated the binding, but I still get the same result. Somewhere a NullPointerException is thrown.

```
11:57:14.676 INFO  o.o.b.m.i.MaxCubeBinding[:162]- Cannot find MAX!cube device with serial number 'JEQ0501207'
11:57:14.677 DEBUG o.o.b.m.i.MaxCubeBinding[:171]- Available MAX! devices are:
11:57:14.679 INFO  o.o.b.m.i.MaxCubeBinding[:162]- Cannot find MAX!cube device with serial number 'KEQ0493700'
11:57:14.680 DEBUG o.o.b.m.i.MaxCubeBinding[:171]- Available MAX! devices are:
11:57:14.681 INFO  o.o.b.m.i.MaxCubeBinding[:162]- Cannot find MAX!cube device with serial number 'JEQ0607538'
11:57:14.682 DEBUG o.o.b.m.i.MaxCubeBinding[:171]- Available MAX! devices are:
11:57:14.683 INFO  o.o.b.m.i.MaxCubeBinding[:162]- Cannot find MAX!cube device with serial number 'KEQ0098486'
11:57:14.684 DEBUG o.o.b.m.i.MaxCubeBinding[:171]- Available MAX! devices are:
11:57:14.685 INFO  o.o.b.m.i.MaxCubeBinding[:162]- Cannot find MAX!cube device with serial number 'KEQ0493700'
11:57:14.686 DEBUG o.o.b.m.i.MaxCubeBinding[:171]- Available MAX! devices are:
11:57:24.936 DEBUG o.o.b.m.i.MaxCubeBinding[:74]- === H_Message ===
11:57:24.938 DEBUG o.o.b.m.i.MaxCubeBinding[:75]-       RAW:JEQ0544462,03f482,0113,00000000,0059d40c,01,2b,0d0c0e,0b39,03,0000
11:57:24.939 DEBUG o.o.b.m.i.MaxCubeBinding[:76]-       Reading Time: Sun Jan 14 11:57:00 CET 14
11:57:24.940 DEBUG o.o.b.m.i.MaxCubeBinding[:77]-       Serial number:  JEQ0544462
11:57:24.941 DEBUG o.o.b.m.i.MaxCubeBinding[:78]-       RF address (HEX):03f482
11:57:24.942 DEBUG o.o.b.m.i.MaxCubeBinding[:79]-       Firmware version:0113
11:57:24.943 DEBUG o.o.b.m.i.MaxCubeBinding[:80]-       Connection ID: 0059d40c
11:57:24.985 DEBUG o.o.b.m.i.MaxCubeBinding[:28]- === M_Message ===
11:57:25.086 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
11:57:25.187 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
11:57:25.189 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
11:57:25.190 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
11:57:25.192 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
11:57:25.285 DEBUG o.o.b.m.i.MaxCubeBinding[:50]- === L_Message ===
11:57:25.296 INFO  o.o.b.m.i.MaxCubeBinding[:148]- Failed to process message received by MAX! protocol.
11:57:25.299 DEBUG o.o.b.m.i.MaxCubeBinding[:149]- java.lang.NullPointerException
        at org.openhab.binding.maxcube.internal.message.Device.create(Device.java:90)
        at org.openhab.binding.maxcube.internal.message.L_Message.getDevices(L_Message.java:42)
        at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:136)
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:176)
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:193)
```

**Comment by aheil** [comment]
Hi Till,

thanks for the feedback. After reviewing the code, I have two ideas about this issue: 

a) the L message was changed with protocol version 1.13 (which I don't hope so) 
b) you have a device which is not yet supported

We currently support shutter contacts and thermostats. Do you have anything else such as a Thermostat+, Wallmounted Thermostat, Eco Shutter or  the new MAX! Power Connector? If so I will add this device. 

Otherwise this issue might arise from parsing of the L message. If there is any difference in the message we can add support for v 1.13 (to avoid breaking backwards capability), however, this would include understanding the changes of the protocol. 

If you don't have any of the above devices, is there any possibility flash your cube with firmware 1.12  again? If the binding would work then, we could be sure about the protocol changes.

I am currently integrating the send command support. Once I've completed this, I can try to upgrade the firmware as well.

**Comment by dereulenspiegel** [comment]
Hi Andreas,

indeed I have Thermostat+ in my Kitchen and a Wallthermostat in my Bedroom both linked to my Cube. Didn't knew that this could cause problems. Would be great to add support to these two (at least to a degree that prevents these devices from crashing the binding).

**Comment by dereulenspiegel** [comment]
Hi Andreas,

I just updated to the latest version of your binding and now the log message changed. Thermostat+ and WallThermostat seem to be support, but the NPE persists.

```
16:16:54.067 DEBUG o.o.b.m.i.MaxCubeBinding[:74]- === H_Message ===
16:16:54.069 DEBUG o.o.b.m.i.MaxCubeBinding[:75]-       RAW:             JEQ0544462,03f482,0113,00000000,047f8202,01,32,0d0c11,1110,03,0000
16:16:54.103 DEBUG o.o.b.m.i.MaxCubeBinding[:76]-       Reading Time:    Wed Jan 17 17:16:00 UTC 14
16:16:54.105 DEBUG o.o.b.m.i.MaxCubeBinding[:77]-       Serial number:   JEQ0544462
16:16:54.107 DEBUG o.o.b.m.i.MaxCubeBinding[:78]-       RF address (HEX):03f482
16:16:54.109 DEBUG o.o.b.m.i.MaxCubeBinding[:79]-       Firmware version:0113
16:16:54.110 DEBUG o.o.b.m.i.MaxCubeBinding[:80]-       Connection ID:   047f8202
16:16:54.144 DEBUG o.o.b.m.i.MaxCubeBinding[:91]- === M_Message ===
16:16:54.146 DEBUG o.o.b.m.i.MaxCubeBinding[:92]-       RAW:00,01,VgICAQxTY2hsYWZ6aW1tZXIHaEMCBkvDvGNoZQl4hwQBB2hDS0VRMDA5ODQ4NgxUaGVybW9zdGF0IDEBBAYj7EpFUTA2MDc1MzgQRmVuc3RlcmtvbnRha3QgMQEDBYF0SkVRMDUwMTIwNxBXYW5kdGhlcm1vc3RhdCAxAQIJeIdLRVEwNDkzNzAwClRoZXJtb3N0YXQCAQ==
16:16:54.222 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
16:16:54.237 DEBUG o.o.b.m.i.MaxCubeBinding[:100]-      RAW:        03f482,7QP0ggATAf9KRVEwNTQ0NDYyAAsABEAAAAAAAAAAAP///////////////////////////wsABEAAAAAAAAAAQf///////////////////////////2h0dHA6Ly9tYXguZXEtMy5kZTo4MC9jdWJlADAvbG9va3VwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAENFVAAACgADAAAOEENFU1QAAwACAAAcIA==
16:16:54.239 DEBUG o.o.b.m.i.MaxCubeBinding[:101]- DeviceType:   Invalid
16:16:54.240 DEBUG o.o.b.m.i.MaxCubeBinding[:102]- SerialNumber: JEQ0544462
16:16:54.242 DEBUG o.o.b.m.i.MaxCubeBinding[:103]- RFAddress:    03f482
16:16:54.316 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
16:16:54.317 DEBUG o.o.b.m.i.MaxCubeBinding[:100]-      RAW:        058174,zgWBdAMBEP9KRVEwNTAxMjA3KiI9CUQ8VFFFAVUNRSBFIEUgRSBFIEUgRSBFIEUgRDxUUUUBVQ1FIEUgRSBFIEUgRSBFIEUgRSBEPFRRRQFVDUUgRSBFIEUgRSBFIEUgRSBFIEQ8VFFFAVUNRSBFIEUgRSBFIEUgRSBFIEUgRDxUUUUBVQ1FIEUgRSBFIEUgRSBFIEUgRSBEPFRRRQFVDUUgRSBFIEUgRSBFIEUgRSBFIEQ8VFFFAVUNRSBFIEUgRSBFIEUgRSBFIEUgBxgw
16:16:54.321 DEBUG o.o.b.m.i.MaxCubeBinding[:101]- DeviceType:   Wallmounted Thermostat
16:16:54.324 DEBUG o.o.b.m.i.MaxCubeBinding[:102]- SerialNumber: JEQ0501207
16:16:54.326 DEBUG o.o.b.m.i.MaxCubeBinding[:103]- RFAddress:    058174
16:16:54.329 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
16:16:54.332 DEBUG o.o.b.m.i.MaxCubeBinding[:100]-      RAW:        076843,0gdoQwEBFv9LRVEwMDk4NDg2KiI9CQcYAzIM/wBEPFRRRQFVDUUgRSBFIEUgRSBFIEUgRSBFIEQ8VFFFAVUNRSBFIEUgRSBFIEUgRSBFIEUgRDxUUUUBVQ1FIEUgRSBFIEUgRSBFIEUgRSBEPFRRRQFVDUUgRSBFIEUgRSBFIEUgRSBFIEQ8VFFFAVUNRSBFIEUgRSBFIEUgRSBFIEUgRDxUUUUBVQ1FIEUgRSBFIEUgRSBFIEUgRSBEPFRRRQFVDUUgRSBFIEUgRSBFIEUgRSBFIA==
16:16:54.334 DEBUG o.o.b.m.i.MaxCubeBinding[:101]- DeviceType:   Thermostat
16:16:54.336 DEBUG o.o.b.m.i.MaxCubeBinding[:102]- SerialNumber: KEQ0098486
16:16:54.338 DEBUG o.o.b.m.i.MaxCubeBinding[:103]- RFAddress:    076843
16:16:54.341 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
16:16:54.343 DEBUG o.o.b.m.i.MaxCubeBinding[:100]-      RAW:        097887,0gl4hwICEP9LRVEwNDkzNzAwKCA9CQcYAzQM/wBASkEJQSBBIEEgQSBBIEUgRSBFIEUgRSBFIEBKQQlBIEEgQSBBIEEgRSBFIEUgRSBFIEUgQEpBCUEgQSBBIEEgQSBFIEUgRSBFIEUgRSBASkEJQSBBIEEgQSBBIEUgRSBFIEUgRSBFIEBKQQlBIEEgQSBBIEEgRSBFIEUgRSBFIEUgQEpBCUEgQSBBIEEgQSBFIEUgRSBFIEUgRSBASkEJQSBBIEEgQSBBIEUgRSBFIEUgRSBFIA==
16:16:54.345 DEBUG o.o.b.m.i.MaxCubeBinding[:101]- DeviceType:   Thermostat+
16:16:54.347 DEBUG o.o.b.m.i.MaxCubeBinding[:102]- SerialNumber: KEQ0493700
16:16:54.349 DEBUG o.o.b.m.i.MaxCubeBinding[:103]- RFAddress:    097887
16:16:54.351 DEBUG o.o.b.m.i.MaxCubeBinding[:99]- === C_Message ===
16:16:54.353 DEBUG o.o.b.m.i.MaxCubeBinding[:100]-      RAW:        0623ec,EQYj7AQBEw9KRVEwNjA3NTM4
16:16:54.355 DEBUG o.o.b.m.i.MaxCubeBinding[:101]- DeviceType:   Shutter Contact
16:16:54.356 DEBUG o.o.b.m.i.MaxCubeBinding[:102]- SerialNumber: JEQ0607538
16:16:54.358 DEBUG o.o.b.m.i.MaxCubeBinding[:103]- RFAddress:    0623ec
16:16:54.414 DEBUG o.o.b.m.i.MaxCubeBinding[:50]- === L_Message ===
16:16:54.416 DEBUG o.o.b.m.i.MaxCubeBinding[:51]-       RAW:DAWBdAkSGAEiAAAAwAsHaEMJEhgAIgAAAAsJeIcJEhkAJADRAAYGI+wJEhA=
16:16:54.438 INFO  o.o.b.m.i.MaxCubeBinding[:184]- Failed to process message received by MAX! protocol.
16:16:54.441 DEBUG o.o.b.m.i.MaxCubeBinding[:185]- java.lang.NullPointerException
        at org.openhab.binding.maxcube.internal.message.Device.create(Device.java:93)
        at org.openhab.binding.maxcube.internal.message.L_Message.getDevices(L_Message.java:42)
        at org.openhab.binding.maxcube.internal.MaxCubeBinding.execute(MaxCubeBinding.java:173)
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:176)
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:193)
```

**Comment by dereulenspiegel** [comment]
Hi Andreas,

I took the liberty of trying to fix the NPE (https://github.com/dereulenspiegel/openhab/tree/maxcube). I hope the way of fixing this is done in a way you see fit. Getting the current desired temp seems to be working for now, but sending commands still seems to be broken. Also getting the current valve opening does seem to be working on the Heatthermostat but not the Heatthermostat+

**Comment by marcelrv** [comment]
Hi Till,

Maybe you can checkout the latest version I think it fixes your temp & valve opening reading for the Heatthermostat+
At least for me it works now.

**Comment by dereulenspiegel** [comment]
Basically this seems to work now. So I think I can close this issue.
