### ISSUE TITLE
Implement S command restricitons

### ISSUE THREAD

**Issue by aheil** [aheil/openhab#4]
Note that the MAX Cube has a lock out that only allows a maximum of 36s of transmissions (1%) in total in 1 hour. This means that if too many S messages are sent then the cube no longer sends the data out. 

If possible, a mechanism should probably be implemented to stop rules sending
too many messages via this binding.

**Comment by cyclingengineer** [comment]
I was wondering if we could achieve this by only sending commands when we poll the cube for an update. The process would look like this:

1) Get command from OpenHAB to set new state (e.g. of thermostat)
2) Push new state into the internal 'model' of the thermostat and indicate it needs updating
[repeat steps 1/2 until it's time for step 3]
3) When it's time to poll the cube (for example every 60s) we push the new values for devices that have been updated.

Does that sound sensible?

**Comment by aheil** [comment]
I thought about something similar. I haven't fully thought about this. Is the 60 second poll interval confirmed? Actually, I am not sure, but when using my shutter contacts I get updates from the cube in lesse than 60 seconds. However, I haven't tested this in any reliable manner yet.

**Comment by cyclingengineer** [comment]
The radiator thermostats seem to update on a 60s period as the date/time. This is based on the H message date / time output - which for my setup (only radiator thermostats) seems to have a 1 min update period regardless of what I set the polling period to. 

I guess more 'interrupt' style events - like the window shutter - could cause an update outside of the standard period.

**Comment by aheil** [comment]
Won‘t fix
